#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

foamListTimes -rm
rm -rf VTK/
rm -rf constant/polyMesh/