#!/bin/bash

# Clean all compiled libs

wclean libso regulatorLibrary/

for directory in ./bndConditions/*; do
    wclean "$directory"
done

for directory in ./solvers/*; do
    wclean "$directory"
done
